version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: django_jwt
      MYSQL_USER: django_jwt
      MYSQL_PASSWORD: your_password
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      PYTHONUNBUFFERED: '1'
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      PYTHONDONTWRITEBYTECODE: '1'
      PYTHONFAULTHANDLER: '1'
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: django_jwt
      MYSQL_USER: django_jwt
      MYSQL_PASSWORD: your_password
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db

volumes:
  db_data:
